version: '2'
services:
  authdb:
    image: 'mysql/mysql-server:latest'
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=password123
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_ROOT_HOST=*.*.*.*

  