
FROM microsoft/aspnetcore-build:2.0 AS build
RUN npm install -g n
RUN n stable
RUN npm install -g @angular/cli
WORKDIR /src
COPY portefolio.sln ./
COPY portefolio ./portefolio
WORKDIR /src/portefolio/webapp/portefolio
RUN npm install
RUN ng build
WORKDIR /src/portefolio
RUN dotnet restore -nowarn:msb3202,nu1503
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM cobreti/linux_netcore_env:1.0 AS final
COPY --from=publish /app /var/www/portefolio
WORKDIR /var/www/portefolio
ENTRYPOINT ["dotnet", "portefolio.dll"]
